name: Node.js CI

on: [push]
defaults:
  run:
    working-directory: ./javascript
env:
  LOOK: HANDSOME

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: this is a ${{ LOOK }} guy!!
        run: echo "YOYO PP tuk kon"
      - name: is a ${{LOOK}} apple?
        run: echo "dkfjsgndfsjklgniosldfghcmsiodl"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test